"""Agents, knowledge bases and toolsets

Revision ID: 9d2ac81c6a0c
Revises: 240ce636f8e4
Create Date: 2025-12-07 20:15:45.571882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d2ac81c6a0c'
down_revision: Union[str, None] = '240ce636f8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('contextualize_system_prompt', sa.Text(), nullable=False),
    sa.Column('enum_model', sa.String(length=64), nullable=False),
    sa.Column('max_response_tokens', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('history_message_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent'))
    )
    op.create_table('knowledge_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_base'))
    )
    op.create_table('toolset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enum_toolset_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mcp_server_url', sa.String(), nullable=True),
    sa.Column('mcp_server_auth_header', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enum_np_toolset', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_toolset'))
    )
    op.create_table('agent_knowledge_base_association',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name=op.f('fk_agent_knowledge_base_association_agent_id_agent')),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], name=op.f('fk_agent_knowledge_base_association_knowledge_base_id_knowledge_base')),
    sa.PrimaryKeyConstraint('agent_id', 'knowledge_base_id', name=op.f('pk_agent_knowledge_base_association'))
    )
    op.create_table('agent_toolset_association',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('toolset_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name=op.f('fk_agent_toolset_association_agent_id_agent')),
    sa.ForeignKeyConstraint(['toolset_id'], ['toolset.id'], name=op.f('fk_agent_toolset_association_toolset_id_toolset')),
    sa.PrimaryKeyConstraint('agent_id', 'toolset_id', name=op.f('pk_agent_toolset_association'))
    )
    op.create_table('file',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enum_status', sa.String(), nullable=False),
    sa.Column('enum_type', sa.String(), nullable=True),
    sa.Column('num_pages', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], name=op.f('fk_file_knowledge_base_id_knowledge_base')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file'))
    )
    op.create_table('tool',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enum_tool_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('webhook_auth_header', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('webhook_query_params_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('webhook_path_params_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('webhook_body_params_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('webhook_http_method', sa.String(), nullable=True),
    sa.Column('mcp_title', sa.String(), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nplabs_tool_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('target_agent_id', sa.UUID(), nullable=True),
    sa.Column('toolset_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['target_agent_id'], ['agent.id'], name=op.f('fk_tool_target_agent_id_agent')),
    sa.ForeignKeyConstraint(['toolset_id'], ['toolset.id'], name=op.f('fk_tool_toolset_id_toolset')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool'))
    )
    op.create_index('idx_tool_toolset_id', 'tool', ['toolset_id'], unique=False)
    op.create_table('chunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('seq_num', sa.Integer(), nullable=False),
    sa.Column('values', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('num_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], name=op.f('fk_chunk_file_id_file')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk')
    op.drop_index('idx_tool_toolset_id', table_name='tool')
    op.drop_table('tool')
    op.drop_table('file')
    op.drop_table('agent_toolset_association')
    op.drop_table('agent_knowledge_base_association')
    op.drop_table('toolset')
    op.drop_table('knowledge_base')
    op.drop_table('agent')
    # ### end Alembic commands ###
